# Generated by Django 4.2.11 on 2024-05-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('semestre 1', 'semestre 1'), ('semestre 2', 'semestre 2')], default=None, max_length=11),
            preserve_default=False,
        ),
    ]
