# Generated by Django 4.2.11 on 2024-05-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0002_module_coef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='module',
            name='horaire',
        ),
    ]
