# Generated by Django 4.2.11 on 2024-05-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_app', '0002_remove_professor_modules_id'),
        ('module_app', '0002_module_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='professor_app.professor'),
        ),
    ]
