# Generated by Django 4.2.11 on 2024-05-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0003_remove_module_contenu_remove_module_enseignant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
