# Generated by Django 4.2.11 on 2024-05-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0004_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_app.year'),
        ),
    ]
