# Generated by Django 4.2.11 on 2024-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0005_module_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('year1', '1CPI'), ('year2', '2CPI'), ('year3', '1CS'), ('year4', '2CS'), ('year5', '3CS')], max_length=10, unique=True),
        ),
    ]
