# Generated by Django 4.2.11 on 2024-05-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_year_alter_student_year'),
        ('module_app', '0006_alter_year_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
