# Generated by Django 4.2.11 on 2024-05-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0006_alter_year_year'),
        ('student_app', '0002_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='module_app.year'),
            preserve_default=False,
        ),
    ]
