# Generated by Django 4.2.11 on 2024-05-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0008_year_module_year'),
        ('student_app', '0004_year_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_app.year'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
