# Generated by Django 4.2.11 on 2024-05-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='modules_id',
        ),
    ]
