# Generated by Django 4.2.11 on 2024-05-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_app', '0004_alter_professor_modules_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='modules_id',
        ),
    ]
