# Generated by Django 5.0.4 on 2024-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('C', 'Course'), ('TD', 'Tutorial'), ('TP', 'Practical Work'), ('A', 'Assignment')], max_length=2)),
                ('file', models.FileField(upload_to='resources/')),
            ],
        ),
    ]
