# Generated by Django 5.0.4 on 2024-04-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_resource_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('C', 'Course'), ('TD', 'Tutorial'), ('TP', 'Practical Work'), ('A', 'Assignment'), ('Q', 'Quiz')], max_length=2),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(blank=True, max_length=100)),
                ('option_2', models.CharField(blank=True, max_length=100)),
                ('option_3', models.CharField(blank=True, max_length=100)),
                ('option_4', models.CharField(blank=True, max_length=100)),
                ('correct_option', models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
            ],
        ),
    ]
