# Generated by Django 5.0.4 on 2024-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_resource_file_alter_resource_resource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('C', 'Course'), ('TD', 'Tutorial'), ('TP', 'Practical Work'), ('H', 'Homework'), ('Q', 'Quiz')], max_length=2),
        ),
    ]
