# Generated by Django 4.2.11 on 2024-04-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='staff_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='file',
            name='age',
        ),
        migrations.RemoveField(
            model_name='file',
            name='position',
        ),
        migrations.RemoveField(
            model_name='file',
            name='year_joined',
        ),
    ]
