# Generated by Django 4.2.11 on 2024-05-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_myuser_is_student_myuser_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='password',
            new_name='role',
        ),
    ]
