# Generated by Django 4.2.11 on 2024-05-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_teacher',
            new_name='is_professor',
        ),
    ]
