# Generated by Django 4.2.11 on 2024-05-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_rename_is_teacher_myuser_is_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
