# Generated by Django 4.2.11 on 2024-05-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_app', '0002_module_coef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('C', 'Course'), ('TD', 'Tutorial'), ('TP', 'Practical Work'), ('A', 'Assignment'), ('Q', 'Quiz')], max_length=2)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_app.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(blank=True, max_length=100)),
                ('option_2', models.CharField(blank=True, max_length=100)),
                ('option_3', models.CharField(blank=True, max_length=100)),
                ('option_4', models.CharField(blank=True, max_length=100)),
                ('correct_option', models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_app.resource')),
            ],
        ),
    ]
