# Generated by Django 5.0.4 on 2024-05-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_alter_resource_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_4',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The score or percentage this question is worth.', max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='resource.quizquestion')),
            ],
        ),
    ]
