# Generated by Django 5.0.4 on 2024-04-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_app', '0001_initial'),
        ('professor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_app.professor'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
