# Generated by Django 4.2.11 on 2024-04-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_app', '0001_initial'),
        ('forums_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_app.professor'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
