# Generated by Django 4.2.11 on 2024-05-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0003_remove_module_contenu_remove_module_enseignant_and_more'),
        ('forums_app', '0002_alter_forum_professor_delete_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='subject',
        ),
        migrations.AddField(
            model_name='forum',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='module_app.module'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
