# Generated by Django 4.2.11 on 2024-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_app', '0003_remove_forum_subject_forum_module_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
