# Generated by Django 4.2.11 on 2024-05-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums_app', '0004_forum_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='professor',
        ),
    ]
